<%@ Page Title="" Language="C#" MasterPageFile="~/preInit/Activity.Master" AutoEventWireup="true" CodeBehind="Terms.aspx.cs" Inherits="mCloud.preInit.Terms" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolderContent" runat="server">
     <section id="Section1" class="features" style="padding: 31px;background-color: rgba(232, 232, 232, 0.34);margin-top: 61px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="section-heading" style="margin-bottom:50px;">
                        <h1 style="color:black;">MOILCLOUD TERMS OF SERVICE </h1>
                     <h4 style="text-align:center;" ><b>ATTENTION: THIS IS A CONTRACT</b> </h4>
                        <h5 style="text-align:justify;" >PLEASE READ THESE TERMS CAREFULLY BEFORE USING THIS WEBSITE. THIS AGREEMENT GOVERNS YOUR RELATIONSHIP WITH MOILCLOUD, AND USE OF THE SERVICES, AS DEFINED BELOW, PROVIDED TO YOU BY MOILCLOUD. YOU ARE HEREBY ASKED TO ACCEPT THESE TERMS OF SERVICE AND MAY USE THE SERVICES AVAILABLE ON THIS WEBSITE ONLY ON CONDITION THAT YOU ACCEPT ALL OF THE TERMS AND CONDITIONS CONTAINED HEREIN. USING THIS  WEBSITE INDICATES THAT YOU ACCEPT THESE TERMS. IF YOU DO NOT ACCEPT THESE  TERMS, DO NOT USE THIS WEBSITE. THESE TERMS OF SERVICE INCLUDE MOILCLOUD'S PRIVACY POLICY AVAILABLE AT WWW.MOILCLOUD.COM/PRIVACY/ WHICH IS INCORPORATED AND MADE A PART OF THESE TERMS OF SERVICE. BY ACCESSING OR USING THIS WEBSITE, YOU AGREE TO BE BOUND BY THESE TERMS OF SERVICE, INCLUDING MOILCLOUD'S PRIVACY POLICY. </h5>


                       
                        <hr style="max-width: 1067px; border-color:#b9b7b7;"/>
                    </div>
                </div>
            </div>
            <div class="row">
                
                <div class="col-md-12">
                    <div class="container-fluid">
                        <h2 style="font-size: 35px;">Moil Cloud Makes Your Privacy a Top Priority</h2>
                        <p class="text-muted">In today's online environment, we understand how important it is to protect our customer's privacy. You can rest assured that Moil Cloud is committed to safeguarding your data and personal information. </p>
                        <h3>Acceptance of Terms of Service </h3>
                        <p class="text-muted">These Terms of Service (the "Agreement" or "Terms of Service") are a legal agreement between you, either an individual or an entity ("you" or "user"), and Moil cloud, Inc. ( "Moil cloud" ), regarding the Services, as defined below. Moil cloud makes this website  (https://www.Moilcloud.com or https://www.Moilcloud.in) and all other Moil cloud domains included within this website (the "Website" ), including all information, graphics, documents, text, products and all other elements of the Website and all products offered on this Website and services operated through the Website, available for your use subject to the terms and conditions set forth in this document. By accessing and using this Website, using any Moil cloud services and/or downloading or purchasing any Moil cloud products, you agree to be bound by and to accept these Terms of Service and all terms and conditions contained and/or referenced herein or any additional terms and conditions set forth on this Website.  If you do NOT agree to all these Terms of Service, you should NOT use this Website. If you do NOT agree to any additional specific terms which apply to particular Content (as defined below) or to particular transactions concluded through this Website, then you should NOT use the part of the Website which contains such Content or through which such transactions may be concluded and you should NOT use such Content or conclude such transactions. Also, when you use any current or future Moil cloud services or visit Moil cloud’s or its affiliates' websites or obtain any products or services, whether free of charge or for payment, of Moil cloud or any business affiliated with Moil cloud, whether or not included in the Website, you will be subject to the guidelines and conditions applicable to such services or business.  
These Terms of Service may be amended by Moil cloud at any time upon notice given by any of the following means: through the Website at or after you login to your User Account (as defined below), by email communication to the address provided by you when you set up your User Account. Failure to provide or maintain accurate or current contact information by you will not obviate your responsibility to comply with these Terms of Service as amended from time to time. Please check these Terms of Service published on this Website regularly to ensure that you are aware of all terms governing your use of this Website. Also, specific terms and conditions may apply to non-user generated specific content, products, materials, services or information contained on or available through this Website (the "Content") or transactions concluded through this Website. Such specific terms may be in addition to these Terms of Service or, where inconsistent with these Terms of Service such specific terms will supersede these Terms of Service only to the extent that the content or intent of such specific terms is inconsistent with these Terms of Service.   
Moil cloud reserves the right to make changes or updates with respect to or in the Content of the Website or the format thereof at any time without notice. Moil cloud reserves the right to terminate or restrict access to the Website or any portion thereof for any reason whatsoever at its sole discretion.   </p>
                        <h3>Users' Obligations </h3>
                        <p class="text-muted">You agree to use the Website, [Moil cloud Apps], and Services only for purposes permitted by these Terms of Service as well as any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdictions. MOILCLOUD IS NOT RESPONSIBLE FOR ANY VIOLATION OF APPLICABLE LAWS, RULES, OR REGULATIONS COMMITTED BY YOU OR A THIRD PARTY AT YOUR BEHEST. IT IS YOUR RESPONSIBILITY TO ENSURE THAT YOUR  USE OF THE WEBSITE, [MOILCLOUD APPS], AND SERVICES DOES NOT CONTRAVENE APPLICABLE LAWS, RULES, OR REGULATIONS. Specifically, you agree and warrant that in using the Website and Services, your actions do not contravene the laws, rules, or regulations of (1) the country, state, or locality where you reside, or (2) the country, state, or locality where 
Moil cloud is located or operates. This includes complying with applicable export and import restrictions as well as other restrictions </p>
                        <h3>Description of Services </h3>
                        <p class="text-muted">Moil cloud enables you to collaborate on projects using a social, cloud-based platform. Companies and individuals alike can use the Moil cloud platform to share confidential files from any location in a secure environment. Managers can create tasks for their employees, upload relevant documents, and coordinate with colleagues to complete projects both effectively and efficiently. Essentially, Moil cloud provides companies with a hub to communicate, collaborate, and create in a secure and accessible virtual, cloud-based environment.   </p>
                        <h3>Use of the Services by You </h3>
                        <p class="text-muted">You agree to use the Services only for purposes permitted by these Terms of Service as well as any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdictions. You agree not to access (or attempt to access) any of the Services by any means other than through the means that is provided by Moil cloud or its authorized partners. You agree not to access or attempt to access any of the Services by way of automated means and that you will not engage in any activity that interferes with or disrupts the Services (or the servers and networks which are connected to the Services).  </p>
                        <ul>Further, you agree: 
                            <li><p>not to disrupt or interfere with any other user's enjoyment of the Website, the Services, or affiliated or linked sites;</p> </li>
                            <li><p>not to upload, post, or otherwise transmit through the Website or the Services any viruses or other harmful, disruptive, or destructive files;</p></li>
                            <li><p>not to use or attempt to use another user's User Account, password, or system;</p></li>
                            <li><p>not to access or attempt to access any Content or User Content (as defined below), which you are not authorized to access under the terms herein;</p></li>
                            <li><p>not to disrupt or interfere with the security of, or otherwise cause harm to, the Website, Services, Content, User Content, system resources, accounts, passwords, servers, or networks connected to or accessible through this Website or any affiliated or linked sites</p></li>
                        </ul>
                        <h3>User Content </h3>
                        <p class="text-muted">User Account holders with Moil cloud may upload data, information, material, and documents to be stored and associated with User Accounts on the Website ("User Content"). Subject to these Terms of Service, your User Content may be used in any manner that has been authorized by you. It is your sole responsibility to determine what additional limitations, if any, are placed on the use of the User Content distributed within your working group. If you obtain unauthorized access to materials created or used by others outside of your working group in conjunction with the Moil cloud Service, you have no right to use such materials in any way. You also acknowledge and agree that Moil cloud has no liability of any kind should members of your working group, other persons whom you have allowed to have access to your User Content or any third party modify, destroy, corrupt, copy, or distribute your User Content. 
Moil cloud does not own any User Content and will not monitor, edit, or disclose any information regarding you or your User Account, including any User Content, without your prior permission except in accordance with these Terms of Service or Privacy Policy (http://www.Moilcloud.com/privacy). Moil cloud also does not review, inspect, edit or monitor any User Content stored by you or any other user of the Services, including, without limitation, for viruses, worms, "Trojan horses" or any other similar contaminating or destructive features. Moil cloud reserves the right, solely upon its own discretion, to refuse, remove or disable access to User Content stored on Moil cloud' servers that Moil cloud learns may be illegal or may violate the terms of these Terms of Service, although it has no obligation to do so.  You are solely responsible for protecting the information on your computer or your other devices for example, by installing anti-virus software, updating your applications, password protecting your files, and preventing third party access to your computer. You understand that users of Moil cloud Services may store User Content that is unusable due to corruption from viruses, software malfunctions or other causes. Moil cloud is not responsible for any damage that any user may incur through the sharing and use of such User Content. </p>
                        <h3>Your Passwords and Account Security </h3>
                        <p class="text-muted">Moil cloud requires you to create a user account ("User Account") in order to use its Services and may also, from time to time, provide you with additional codes or passwords necessary to access and use certain other features or functions of the Website. In creating your User Account, you agree to submit accurate, current and complete information about yourself and keep such information updated. Moil cloud reserves the right to suspend or terminate accounts which are reasonably suspected to be used in contradiction to the terms herein and/or contain information that is untrue, inaccurate, not current or incomplete. </p>
                         <p class="text-muted">You may also access the Website, [Moil cloud Apps,] and Service by logging in using an authorized third party social network account, such as a Face book or Twitter account. By doing so, you authorize Moil cloud to collect your personal profile and activity information from that third party social network. </p>
                        <p class="text-muted">Please note that if you opt to use your Face book account to login to our Website and/or Moil cloud Apps and use our Services or interact with other user of the Website, Moil cloud is able to access all of your data in connection with your Face book account, including, without limitation your friends list, pictures you posted or those posted of you on Face book, businesses and stories you 'liked', places you visited, etc.</p>
                         <p class="text-muted">This information you provide is used for such purposes as allowing you to set up a user Account and profile that can be used to interact with other users through the Service, improving the content of the Service, customizing the advertising and content you see, and communicating with you about specials and new features. It is completely optional for you to engage in these activities and/or make any purchases from Moil cloud. </p>
                        <p class="text-muted">You shall choose a personal, non-transferable password. User Accounts may not be "shared" or used by more than one individual. After you accept these Terms of Service and your User Account registration has been accepted by Moil cloud, your User Account will be established. You are solely responsible for any and all activities that occur under your User Account, whether or not such use was authorized by you</p>

                        <h3>Communicating with Other Users </h3>
                        <p class="text-muted">The Website, Moil cloud Apps, and Services may allow you to communicate with other users through a third party VMA or other means. Discretion should be used when disclosing any information through these means, as it may be accessed by third parties. Use of any personally identifiable information, and your options regarding our use of this information, are subject to Moil cloud’s Privacy Policy.   </p>
                        <h3>Security of User Content </h3>
                        <p class="text-muted">Moil cloud will use all commercially reasonable efforts to restrict access to your User Content to authorized persons. However, no password-protected system of data storage and retrieval can be made entirely impenetrable. Although Bixtrix24 strives to make sure that all data on the Website is secure, you hereby acknowledge and accept that it may be possible for an unauthorized third party to access, view, copy, modify and distribute the data and files you store on the Website or via Services.   </p>
                        <h3>Technical Support </h3>
                        <p class="text-muted">Moil cloud maintains a community resource for all users on its website which contains frequently asked questions and other useful information concerning the product and its use. In addition, Moil cloud will provide technical support for paying account holders of its Services and its Software (defined below). In order to receive technical support from Moil cloud, the user seeking such support must request such support by contacting Moil cloud using the helpdesk feature  at  http://www.Moilcloud.com The user should describe the nature of the problem to be resolved as well as providing information about the user (name, address, etc). Moil cloud will make reasonable efforts to respond to such requests in a timely manner,. The user will cooperate with Moil cloud when seeking technical support services by providing information necessary to assist Moil cloud or requested by Moil cloud while diagnosing or resolving the issue. Although Moil cloud cannot guarantee that a technical support issue will be resolved, Moil cloud will make reasonable efforts to perform technical support services in a professional manner</p>
                        <h3>Fees and Payment </h3>
                        <p class="text-muted">All rights and privileges provided herein to you under these Terms of Service are subject to your payment of applicable fee, if any, to Moil cloud, provided however, that Moil cloud expressly reserves the right to provide the Services free of charge during the Term, and further provided, that Moil cloud, solely at its own discretion and upon termination of this Agreement, may elect to provide the same or similar Services for a fee. </p>
                          <p class="text-muted">Payment for Services shall be at prices as agreed upon between you and Moil cloud. Moil cloud offers multiple Service Plans for users, with different fees and functionality features for each plan ("Service Plan"). Payment for a Service Plan, if any, shall be made in advance and is nonrefundable, that is there will be no refunds, full or partial. </p>
                          <p class="text-muted">For instance, if you cancel your subscription to your Service plan before it ends, you will still be responsible for paying any applicable fees for the remainder of the selected subscription period. All fees are exclusive of taxes, levies, or duties imposed by taxing authorities; you are responsible for paying any such applicable tax. </p>
                         <p class="text-muted">You acknowledge that the amount billed for the subscription may vary for reasons that include, differing amounts due to promotional offers, differing amounts due to changes in your account, or changes in the amount of applicable sales tax, and you authorize us to bill you for such varying amounts.   </p>
                        <p class="text-muted">Pre-paid telephony or VoIP credit that you can use for outbound phone calls or phone number rental services has no cash value, is non-refundable and non-transferable, either. If your account or telephone number is terminated or suspended for any reason, you may not be able to use remaining telephony or VoIP credit. No refund of unused VoIP or telephony credit can be provided. Nor can remaining credit be transferred to another account, allocated against outstanding invoices, or used as payment for another service</p>
                        <p class="text-muted">In case of non-payment for any reason, Moil cloud reserves the right to immediately bar the User's access to the Services. </p>
                        <h3>Information and Materials Provided By You </h3>
                        <p class="text-muted">All materials, documents, communications, or information submitted to, sent through, or stored on this Website by you will be subject to these Terms of Service and Privacy Policy (http://www.Moilcloud.com/privacy). The security of such information is very importance to Moil cloud.   </p>
                        <h3>Term/Termination </h3>
                        <p class="text-muted">The term of these Terms of Service ("Term") shall begin when you start using this Website or the Services and shall continue in perpetuity unless otherwise terminated by Moil cloud or you by written notice. Moil cloud reserves the right to change, suspend or discontinue the Services or any portion thereof, at any time. Without prejudice to any other rights, these Terms of Service will terminate automatically if you fail to comply with any of the limitations or other requirements described herein. Upon any termination or expiration of these Terms of Service, you must immediately cease using this Website and the Services including without limitation any use of Moil cloud’s trademarks, trade names, copyrights and other intellectual property.   </p>
                        <p class="text-muted">Upon termination of this agreement you will no longer be authorized to use this website or the services in any way. </p>
                        <h3>Links to Other Sites and Third Party Materials </h3>
                        <p class="text-muted">This Website may provide links to other websites and/or third party products and Services that are not under the control of Moil cloud (together, "Third Party Materials"). Moil cloud shall not be responsible in any way for the content of such Third Party Materials. Moil cloud provides such links only for the convenience of the users of this Website and Services, and the inclusion of any link to any Third Party Materials does not imply endorsement by Moil cloud of the content, products and/ or services of such Third Party Materials. Notwithstanding any provision to the contrary herein, nothing in this Terms of Service shall be construed as to grant you any rights or licenses with regard to such Third Party Materials or to entitle you to use such Third Party Materials.   </p>
                         <h3>Language of the Terms of Service </h3>
                        <p class="text-muted">Where Moil cloud has provided you with a translation of the English language version of these Terms of Service into another language, you agree that the translation is provided for your convenience only and that the English language versions of these Terms of Service will govern your relationship with Moil cloud. If there is any contradiction between the English language version of these Terms of Service and the translation, the English language version shall control. </p>
                        <h3>Intellectual Property</h3>
                        <p class="text-muted">Copyright, trademark and all other proprietary rights in the Website, Content (including but not limited to software, services, audio, video, text and photographs) and/or Services rest with Moil cloud and/or its licensors. Unless otherwise specifically provided herein or authorized by Moil cloud in writing, all rights in the Website, Content and/or Services not expressly granted herein are reserved. You agree not to copy, republish, frame, make available for download, transmit, modify, rent, lease, loan, sell, assign, distribute, license, sublicense, reverse engineer, or create derivative works based on the Content, Website, its products or Services.   </p>
                         <p class="text-muted">Moil cloud hereby disclaims any rights to trademarks, service marks, trade names, logos, copyright, patents, domain names or other intellectual property interests of third parties. All intellectual property interests of third parties referenced herein, including without limitation Third Party Material or otherwise provided on this Website are the properties of their respective owners. Moil cloud disclaims any proprietary interests in the intellectual property rights other than their own.   </p>
                        
                    </div>
                </div>
            </div>
    </div></section>

</asp:Content>

<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolderFooterScript" runat="server">
</asp:Content>
